//errors
export const GET_ERRORS = "GET_ERRORS";

//users
export const SET_CURRENT_USER = "SET_CURRENT_USER";

//authors
export const SHOW_ALL_AUTHORS = "SHOW_ALL_AUTHORS";

//books
export const SHOW_ALL_BOOKS = "SHOW_ALL_BOOKS";
export const SHOW_DETAILED_BOOK = "SHOW_DETAILED_BOOK";
export const BOOK_NOTIFICATION = "BOOK_NOTIFICATION";
export const BOOK_LOADING = "BOOK_LOADING";

//podcasts
export const SHOW_ALL_PODCASTS = "SHOW_ALL_PODCASTS";
export const SHOW_DETAILED_PODCAST = "SHOW_DETAILED_PODCAST";
export const PODCAST_NOTIFICATION = "PODCAST_NOTIFICATION";
export const PODCAST_LOADING = "PODCAST_LOADING";


